import { NextRequest, NextResponse } from "next/server";
import { nftCollectionContractAddress } from "../../utils/contract";

// Hardcoding the environment variables for debugging
const ENGINE_URL = "https://383987b8.engine-usw2.thirdweb.com";
const THIRDWEB_SECRET_KEY = "eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiIweEYyRWY4NUU1MDRjQzc1ZmIyM0ZBQThFNjVDRUFCMDgzRTc2NDFlM2EiLCJzdWIiOiIweDU4MTY2QkJFOEFCZDYyNjBCNzQ5ZDExMTUzMzE2Q2YwNDBGNDE2MjYiLCJhdWQiOiJ0aGlyZHdlYi5jb20iLCJleHAiOjQ4NzY5MzYwOTksIm5iZiI6MTcyMzMzNjA5OSwiaWF0IjoxNzIzMzM2MDk5LCJqdGkiOiJlODY2YTEyYi01MDdkLTQ1MDEtYmYzNy0xZTU4NmNmODVlZGEiLCJjdHgiOnsicGVybWlzc2lvbnMiOiJBRE1JTiJ9fQ.MHhmZjliYTRhOTYyOTJlNzI5NzFiMDhlNWRiOGZjYWY5NzYxNTdkM2U3ODJlMDE4NzMxNDBiYTc0YzUyNjVjOWI3Mjg4MTU5MWVhMWE4NWRhMDZjMGIzMWE5OGY0MmI4ODQyNDVkMzY5NmNjMmQ0NmM3NTJmZjdiOTE5NjhjODMwOTFi";
const BACKEND_WALLET_ADDRESS = "0x58166BBE8ABd6260B749d11153316Cf040F41626";
const CHAIN_ID = "11155111";

export async function POST(req: NextRequest) {
    console.log("POST /api/mint called");

    // Logging the environment variables to check if they are being called properly
    console.log("Environment Variables:");
    console.log("ENGINE_URL:", ENGINE_URL);
    console.log("THIRDWEB_SECRET_KEY:", THIRDWEB_SECRET_KEY ? "*****" : "undefined");
    console.log("BACKEND_WALLET_ADDRESS:", BACKEND_WALLET_ADDRESS);
    console.log("CHAIN_ID:", CHAIN_ID);

    const { nftImage, address } = await req.json();
    console.log("Request body:", { nftImage, address });

    if (!nftImage || !address) {
        console.error("Missing nftImage or address in the request body");
        return NextResponse.json({ error: "Invalid request data" }, { status: 400 });
    }

    try {
        const mintURL = `${ENGINE_URL}/contract/${CHAIN_ID}/0x2b3D19fe7F3B244EBB6A6CFA57071fdF0Eef5266/erc721/mint-to/`;
        console.log("Mint URL:", mintURL);

        const headers = {
            "Content-Type": "application/json",
            Authorization: `Bearer ${THIRDWEB_SECRET_KEY}`,
            "x-backend-wallet-address": BACKEND_WALLET_ADDRESS,
        };
        console.log("Headers:", headers);

        const res = await fetch(mintURL, {
            method: "POST",
            headers: headers,
            body: JSON.stringify({
                receiver: address,
                metadata: {
                    name: "AI NFT",
                    description: "An NFT generated by AI",
                    image: nftImage, // Use the image URL directly
                },
            }),
        });

        const responseData = await res.text();
        console.log("Thirdweb minting response:", responseData);

        if (!res.ok) {
            console.error("Failed to mint NFT:", responseData);
            throw new Error('Failed to mint NFT');
        }

        return NextResponse.json({ data: "NFT minted successfully" });
    } catch (error) {
        console.error("Minting error: ", error);
        return NextResponse.json({ error: "Failed to mint NFT" }, { status: 500 });
    }
}

